# Modified from code by Pujith Kachana, 2025

import os
from abc import ABC, abstractmethod

import torch
import numpy as np


class Featurizer(ABC):
    """ Abstract class for featurizers.
    """
    @abstractmethod
    def __init__(self):
        """ Initialize the featurizer.
        """
        pass

    @abstractmethod
    def init_model(self):
        """ Initialize the model.

        Returns:
            The model.
        """
        pass
        
    @abstractmethod    
    def featurize(
        self, 
        images: torch.Tensor
    ) -> torch.Tensor:
        """ Take a forward pass through the input images and generate features.

        Args:
            images: The input images. Shape: (batch_size, channels, height, width)
        
        Returns:
            features: The features generated by the model. Shape: (batch_size, ...)
        """
        pass
    
    def save_features(
        self, 
        features: torch.Tensor, 
        path: str,
    ):
        """ Save the features to a file.

        Args:
            features: The features to save.
            path: The path to save the features to.
        """
        os.makedirs(os.path.dirname(path), exist_ok=True)
        features = features.detach().cpu().numpy()#.astype(np.float16)
        np.save(path, features)
